#
###################################
# Site wide configuration
####################################
#
title: Joao Santos
email: jm_santos7@hotmail.com
description: A creator's blog.
url: # the base hostname & protocol for your site
keywords:
    [
        "blog",
        "developer",
        "creator",
        "code",
        "frontend",
        "front-end developer",
        "web developer",
        "web",
        "jekyll"
    ]

#
###################################
# Jekyll configuration
####################################
#
timezone: Europe/Lisbon
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /articles/:year-:month/:title

kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
    name: Joao Santos
    avatar: avatar.jpg
    job: "Web developer | Creator"
    bio: "Welcome to my blog.<br />I write articles on code and ideas I have."
    email: jm_santos7@hotmail.com
    disqus-shortname:
    twitter: #username
    facebook: #username
    google:
        plus: #username
        analytics:
        verify:
        ad-client:
        ad-slot:
    bing-verify:
    github: joao-m-santos
    gitlab: #username
    stackoverflow: 7120436/joao-m-santos #123456/username   from a "http://stackoverflow.com/users/123456/username" link
    linkedin: jm-santos
    skype: #username
    xing: #username
    instagram: #username
    lastfm: #username
    tumblr: #username
    pinterest: #username
    foursquare: #username
    steam: #username
    dribbble: #username
    youtube: #username
    soundcloud: #username
    weibo: #username
    flickr: #username
    500px: #username
    codepen: #username
    reddit: #username
    telegram: #username
